[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.x86_64-osel-bios]
runner = "bootimage runner"

[target.x86_64-unknown-uefi]
runner = [
    "qemu-system-x86_64",
    "-drive", "format=raw,file=uefi.img",
    "-bios", "/usr/share/OVMF/OVMF.fd",
    "-serial", "stdio",
    "-display", "none"
]